# platform = multi_platform_ubuntu
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Package facts
  package_facts:

- name: Ensure proper definition for smartcard configuration
  lineinfile:
    path: /etc/pam_pkcs11/pam_pkcs11.conf
    regex: ^(cert_policy)(.*)$
    line: \1 = ca,signature,ocsp_on,crl_auto;
    state: present
    backrefs: true
  when: "'libpam-pkcs11' in ansible_facts.packages"

- name: Add cert policy if it does not exist
  lineinfile:
    path: /etc/pam_pkcs11/pam_pkcs11.conf
    line: cert_policy = ca,signature,ocsp_on,crl_auto;
    state: present
    create: true
  when: 
    - "'libpam-pkcs11' in ansible_facts.packages"
